const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");

const rizzLines = [
  "Are you French? Because Eiffel for you.",
  "If beauty were a crime, you’d be serving a life sentence.",
  "Do you have a map? I just got lost in your eyes.",
  "You must be a magician, because every time I look at you, everyone else disappears.",
  "I was blinded by your beauty... I’m going to need your name and number for insurance purposes.",
  "Your hand looks heavy—can I hold it for you?",
  "Are you a keyboard? Because you’re just my type.",
  "Do you believe in love at first sight—or should I walk by again?",
  "If kisses were snowflakes, I’d send you a blizzard.",
  "You must be tired, because you’ve been running,
  "You look like the reason my phone battery dies faster.",
  "If beauty was a crime, you’d be serving consecutive life sentences.",
  "You talk like the main character, and I kinda wanna be the side quest.",
  "You must be made of Wi-Fi, because I’m feeling a strong connection.",
  "You’re the update I didn’t know my heart needed.",
  "If I had a star for every time you made me smile, I’d own a galaxy.",
  "You could rob me blind, and I’d thank you for the experience.",
  "If we were both emojis, we’d be 🔥 + 😮‍💨.",
  "You’re not Google, but you’ve got everything I’ve been searching for.",
  "You could make a Discord mod forget his server exists.",
  "Your vibe’s got main-character energy written in bold.",
  "I’d risk my 3-day streak just to text you back faster.",
  "You’re so fine, autocorrect changes ‘no’ to ‘yes’.",
  "If you were a DM, I’d reply instantly.",
  "You make loading screens feel worth the wait.",
  "You could make a silent server active again.",
  "You’re proof that perfection actually loads in 4K.",
  "I don’t chase, but for you I’d turn off auto-sprint.",
  "You’re like my favorite playlist — I never skip.",
  "You got more pull than Discord Nitro on sale.",
  "If looks could kill, I’d already be typing /revive.",
  "You could post a blank story and I’d still swipe up.",
  "You got that ‘I don’t try, but it still works’ aura.",
  "If you were lag, I’d still wait for you to reconnect.",
  "You’re the reason ‘typing…’ looks exciting.",
  "You must be a limited-edition drop, because everyone wants you.",
  "You could make a loading screen blush.",
  "You make every other NPC look unrendered.",
  "You’re the kind of person I’d use my last respawn for.",
  "You could make a Discord bot catch feelings.",
];

