const roasts = [
  "Bro, you’re so broke even your Wi-Fi is on layaway.",
  "You look like you Google ‘how to be funny’ before every conversation.",
  "Your mom should’ve named you ‘Buffering’ because you’re always slow.",
  "You got a face that even radio stations would reject.",
  "You look like you still type with one finger.",
  "Your confidence is like your bank account — overdrawn.",
  "You talk so much nonsense you should charge a subscription fee for it.",
  "You look like the before picture in every ad.",
  "Your personality was clearly built using expired software.",
  "You're the reason group chats go silent.",
  "You look like your parents met on Omegle.",
  "Your sense of fashion died and never respawned.",
  "You sound like a YouTube tutorial recorded with a potato.",
  "You're proof evolution sometimes hits pause.",
  "You're so slow that buffering wheels get impatient.",
  "You’ve got that ‘Windows error’ kind of energy.",
  "You look like you’d lose a staring contest with a mirror.",
  "You post motivational quotes but can’t even motivate your charger to stay plugged in.",
  "You look like a failed Roblox avatar.",
  "If I had a dollar for every bad decision you’ve made, I’d own Tesla by now.",
  "Your voice could make text-to-speech sound human.",
  "You look like you eat cereal with water.",
  "You act like Wi-Fi — weak and disappears when needed.",
  "You’re the type of person to trip on wireless internet.",
  "You look like you still use Internet Explorer as a personality trait.",
  "You have the energy of a low battery warning.",
  "You dress like your laundry machine quit on you.",
  "You talk like a TikTok comment section — loud, wrong, and full of bad takes.",
  "You look like you’d apologize to an NPC.",
  "You’re the human version of a lag spike.",
];
